<#
.SYNOPSIS
    Generates MANIFEST.md by scanning _copilot-shared for all artefacts.

.DESCRIPTION
    Reads each subfolder of _copilot-shared (agents, chatmodes, instructions,
    prompts, skills, workflows) and extracts a one-line description from each
    file's YAML frontmatter or H1 heading.

    Produces a Markdown table per category, written to _copilot-shared/MANIFEST.md.

    Called automatically by sync-shared-copilot.ps1 on every sync.

.EXAMPLE
    .\build-manifest.ps1
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Script lives in powershell\ subfolder; _copilot-shared is in the workspace root.
$Root = Join-Path (Split-Path $PSScriptRoot -Parent) "_copilot-shared"
$OutFile = Join-Path $Root "MANIFEST.md"

# -- Helpers -----------------------------------------------------------------

function Get-FrontmatterDescription {
    <#
    .SYNOPSIS
        Extracts the description field from YAML frontmatter.
    .DESCRIPTION
        Reads the file, looks for content between the first pair of --- lines,
        and extracts the description: value. Returns $null if not found.
    #>
    param([string] $FilePath)

    $lines = Get-Content $FilePath -Encoding UTF8
    if ($lines.Count -lt 3) { return $null }
    if ($lines[0].Trim() -ne "---") { return $null }

    $description = $null
    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq "---") { break }
        if ($lines[$i] -match '^\s*description:\s*"?(.+?)"?\s*$') {
            $description = $Matches[1]
        }
    }
    return $description
}

function Get-H1Description {
    <#
    .SYNOPSIS
        Extracts a description from the first H1 and the paragraph after it.
    .DESCRIPTION
        For files without frontmatter (skills, workflows), uses the H1 heading
        text as the name and the first non-empty paragraph line as the description.
    #>
    param([string] $FilePath)

    $lines = Get-Content $FilePath -Encoding UTF8
    $h1 = $null
    $descLine = $null

    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^#\s+(.+)$') {
            $h1 = $Matches[1]
            # Look for ## Purpose heading and grab the line after it
            for ($j = $i + 1; $j -lt $lines.Count; $j++) {
                if ($lines[$j] -match '^##\s+Purpose') {
                    # Grab the next non-empty line
                    for ($k = $j + 1; $k -lt $lines.Count; $k++) {
                        if ($lines[$k].Trim() -ne "") {
                            $descLine = $lines[$k].Trim()
                            break
                        }
                    }
                    break
                }
            }
            break
        }
    }

    if ($h1 -and $descLine) {
        return $descLine
    } elseif ($h1) {
        return $h1
    }
    return $null
}

function Get-Description {
    <#
    .SYNOPSIS
        Gets a description from a file using frontmatter first, then H1 fallback.
    #>
    param([string] $FilePath)

    $desc = Get-FrontmatterDescription -FilePath $FilePath
    if (-not $desc) {
        $desc = Get-H1Description -FilePath $FilePath
    }
    if (-not $desc) {
        $desc = "(no description found)"
    }
    # Truncate long descriptions for readability
    if ($desc.Length -gt 120) {
        $desc = $desc.Substring(0, 117) + "..."
    }
    return $desc
}

function Get-ApplyTo {
    <#
    .SYNOPSIS
        Extracts the applyTo field from instruction file frontmatter.
    #>
    param([string] $FilePath)

    $lines = Get-Content $FilePath -Encoding UTF8
    if ($lines.Count -lt 3) { return $null }
    if ($lines[0].Trim() -ne "---") { return $null }

    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq "---") { break }
        if ($lines[$i] -match '^\s*applyTo:\s*"?(.+?)"?\s*$') {
            return $Matches[1]
        }
    }
    return $null
}

# -- Build the manifest ------------------------------------------------------

$sb = [System.Text.StringBuilder]::new()

$null = $sb.AppendLine("# Copilot Artefact Manifest")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("> **Auto-generated** by ``build-manifest.ps1`` on every sync.")
$null = $sb.AppendLine("> Do not edit this file manually - it will be overwritten.")
$null = $sb.AppendLine(">")
$null = $sb.AppendLine("> Last generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("---")
$null = $sb.AppendLine("")

# --- Agents ---
$null = $sb.AppendLine("## Agents")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("| File | Description |")
$null = $sb.AppendLine("| --- | --- |")

$agentDir = Join-Path $Root "agents"
if (Test-Path $agentDir) {
    Get-ChildItem $agentDir -Filter "*.agent.md" | Sort-Object Name | ForEach-Object {
        $desc = Get-Description -FilePath $_.FullName
        $null = $sb.AppendLine("| ``$($_.Name)`` | $desc |")
    }
}
$null = $sb.AppendLine("")

# --- Chat Modes ---
$null = $sb.AppendLine("## Chat Modes")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("| File | Description |")
$null = $sb.AppendLine("| --- | --- |")

$chatDir = Join-Path $Root "chatmodes"
if (Test-Path $chatDir) {
    Get-ChildItem $chatDir -Filter "*.chatmode.md" | Sort-Object Name | ForEach-Object {
        $desc = Get-Description -FilePath $_.FullName
        $null = $sb.AppendLine("| ``$($_.Name)`` | $desc |")
    }
}
$null = $sb.AppendLine("")

# --- Instructions ---
$null = $sb.AppendLine("## Instructions")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("| File | Applies to | Description |")
$null = $sb.AppendLine("| --- | --- | --- |")

$instrDir = Join-Path $Root "instructions"
if (Test-Path $instrDir) {
    Get-ChildItem $instrDir -Filter "*.instructions.md" | Sort-Object Name | ForEach-Object {
        $desc = Get-Description -FilePath $_.FullName
        $applyTo = Get-ApplyTo -FilePath $_.FullName
        if (-not $applyTo) { $applyTo = "(not specified)" }
        $null = $sb.AppendLine("| ``$($_.Name)`` | ``$applyTo`` | $desc |")
    }
}
$null = $sb.AppendLine("")

# --- Prompts ---
$null = $sb.AppendLine("## Prompts")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("| File | Description |")
$null = $sb.AppendLine("| --- | --- |")

$promptDir = Join-Path $Root "prompts"
if (Test-Path $promptDir) {
    Get-ChildItem $promptDir -Filter "*.prompt.md" | Sort-Object Name | ForEach-Object {
        $desc = Get-Description -FilePath $_.FullName
        $null = $sb.AppendLine("| ``$($_.Name)`` | $desc |")
    }
}
$null = $sb.AppendLine("")

# --- Skills ---
$null = $sb.AppendLine("## Skills")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("| File | Description |")
$null = $sb.AppendLine("| --- | --- |")

$skillDir = Join-Path $Root "skills"
if (Test-Path $skillDir) {
    Get-ChildItem $skillDir -Filter "*.skill.md" | Sort-Object Name | ForEach-Object {
        $desc = Get-Description -FilePath $_.FullName
        $null = $sb.AppendLine("| ``$($_.Name)`` | $desc |")
    }
}
$null = $sb.AppendLine("")

# --- Workflows ---
$null = $sb.AppendLine("## Workflows")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("| File | Description |")
$null = $sb.AppendLine("| --- | --- |")

$workflowDir = Join-Path $Root "workflows"
if (Test-Path $workflowDir) {
    Get-ChildItem $workflowDir -Filter "*.workflow.md" | Sort-Object Name | ForEach-Object {
        $desc = Get-Description -FilePath $_.FullName
        $null = $sb.AppendLine("| ``$($_.Name)`` | $desc |")
    }
}
$null = $sb.AppendLine("")

# --- Tests ---
$null = $sb.AppendLine("## Tests")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("| File | Description |")
$null = $sb.AppendLine("| --- | --- |")

$testDir = Join-Path $Root "tests"
if (Test-Path $testDir) {
    Get-ChildItem $testDir -Filter "*.py" | Sort-Object Name | ForEach-Object {
        # Extract Python module docstring (first triple-quoted string)
        $content = Get-Content $_.FullName -Encoding UTF8 -Raw
        $desc = "(no description)"
        if ($content -match '"""(.+?)"""') {
            $firstLine = ($Matches[1] -split "`n")[0].Trim()
            if ($firstLine.Length -gt 120) { $firstLine = $firstLine.Substring(0, 117) + "..." }
            $desc = $firstLine
        }
        $null = $sb.AppendLine("| ``$($_.Name)`` | $desc |")
    }
}
$null = $sb.AppendLine("")

# -- Write output ------------------------------------------------------------

$content = $sb.ToString().TrimEnd() + "`n"
[System.IO.File]::WriteAllText($OutFile, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "  MANIFEST.md generated ($((Get-ChildItem $OutFile).Length) bytes)" -ForegroundColor DarkGreen
